- name: Collect logs.
  synchronize:
    dest: "{{ zuul.executor.log_root }}/{{ item.dest }}"
    src: "{{ item.src }}"
    mode: pull
  with_items:
    - dest: "console.log"
      src: "{{ base_console_log_file }}"
    - dest: logs
      src: "{{ base_log_root }}"
