- name: Collect logs.
  synchronize:
    dest: "{{ zuul.executor.log_root }}/{{ item.dest }}"
    src: "{{ item.src }}"
    mode: pull
  with_items:
    - dest: logs
      src: "{{ base_log_root }}"

# FIXME(jamielennox): switch back to command after command+delegate_to:
# localhost work together correctly with zuul streaming.
- name: publish logs.
  delegate_to: localhost
  shell: >
    /usr/bin/rsync -q
    --compress --recursive
    --rsh ssh
    --rsync-path 'mkdir -p /var/www/bonny-logs/logs/{{ zuul.tenant }}/{{ zuul.pipeline }}/{{ zuul.project.canonical_name }}/{{ zuul.change }}/{{ zuul.ref }}/{{ zuul.job }} && rsync'
    {{ zuul.executor.log_root }}/
    logs.internal.opentechsjc.bonnyci.org:/var/www/bonny-logs/logs/{{ zuul.tenant }}/{{ zuul.pipeline }}/{{ zuul.project.canonical_name }}/{{ zuul.change }}/{{ zuul.ref }}/{{ zuul.job }}/
