- name: Collect logs.
  synchronize:
    dest: "{{ zuul.executor.log_root }}/{{ item.dest }}"
    src: "{{ item.src }}"
    mode: pull
  with_items:
    - dest: logs
      src: "{{ base_log_root }}"

- name: publish logs.
  become: no
  delegate_to: localhost
  command: >
    /usr/bin/rsync -vvv
    --compress --recursive
    --rsh ssh
    --rsync-path 'mkdir -p {{ bonnyci_logs_dir }}/{{ zuul.tenant }}/{{ zuul.pipeline }}/{{ zuul.project.canonical_name }}/{{ zuul.change }}/{{ zuul.ref }}/{{ zuul.job }} && rsync'
    {{ zuul.executor.log_root }}/
    {{ bonnyci_logs_scp }}:{{ bonnyci_logs_dir }}/{{ zuul.tenant }}/{{ zuul.pipeline }}/{{ zuul.project.canonical_name }}/{{ zuul.change }}/{{ zuul.ref }}/{{ zuul.job }}/
